using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace CDeTDS.DAL
{
    /// <summary>
    /// Shared PDF generation primitives. Sets QuestPDF community license once, exposes
    /// helpers for A4 page setup, branded header/footer, watermarks.
    /// </summary>
    public static class PdfReports
    {
        private static bool _licenseSet;

        /// <summary>Call once at app startup. Sets QuestPDF to Community licence (free for &lt;$1M revenue).</summary>
        public static void Initialize()
        {
            if (_licenseSet) return;
            QuestPDF.Settings.License = LicenseType.Community;
            _licenseSet = true;
        }

        // ── Brand palette ───────────────────────────────────────────────────
        public static readonly string PrimaryColor   = "#1565C0";   // brand blue
        public static readonly string AccentColor    = "#15803d";   // success green
        public static readonly string ErrorColor     = "#dc2626";
        public static readonly string MutedColor     = "#64748b";
        public static readonly string LightBgColor   = "#f8fafc";
        public static readonly string BorderColor    = "#cbd5e1";

        // ── Page wrapper ────────────────────────────────────────────────────
        /// <summary>
        /// A4 portrait page with consistent margins, app footer, page number.
        /// Pass a delegate to render the body — the delegate gets a Container scoped to the page content area.
        /// </summary>
        public static byte[] BuildA4(string title, Action<IContainer> body, string? subtitle = null, bool centerHeader = false, bool landscape = false)
        {
            Initialize();
            return Document.Create(doc =>
            {
                doc.Page(page =>
                {
                    page.Size(landscape ? PageSizes.A4.Landscape() : PageSizes.A4);
                    page.Margin(36);
                    page.DefaultTextStyle(t => t.FontSize(10).FontFamily("Arial"));

                    // Title bar
                    page.Header().Element(c => RenderTitle(c, title, subtitle, centerHeader));

                    // Body — caller fills
                    page.Content().PaddingVertical(8).Element(body);

                    // Footer
                    page.Footer().Element(RenderFooter);
                });
            }).GeneratePdf();
        }

        private static void RenderTitle(IContainer c, string title, string? subtitle, bool centered = false)
        {
            c.Column(col =>
            {
                if (centered)
                {
                    col.Item().AlignCenter().Text(title).FontSize(16).Bold().FontColor(PrimaryColor);
                    if (!string.IsNullOrEmpty(subtitle))
                        col.Item().AlignCenter().Text(subtitle).FontSize(10).FontColor(MutedColor);
                }
                else
                {
                    col.Item().Text(title).FontSize(16).Bold().FontColor(PrimaryColor);
                    if (!string.IsNullOrEmpty(subtitle))
                        col.Item().Text(subtitle).FontSize(10).FontColor(MutedColor);
                }
                col.Item().PaddingTop(4).BorderBottom(1).BorderColor(PrimaryColor);
            });
        }

        private static void RenderFooter(IContainer c)
        {
            c.AlignBottom().Row(row =>
            {
                row.RelativeItem().Text(t =>
                {
                    t.Span("Generated by CDeTDS · ").FontSize(8).FontColor(MutedColor);
                    t.Span(DateTime.Now.ToString("dd-MMM-yyyy HH:mm")).FontSize(8).FontColor(MutedColor);
                });
                row.ConstantItem(100).AlignRight().Text(t =>
                {
                    t.Span("Page ").FontSize(8).FontColor(MutedColor);
                    t.CurrentPageNumber().FontSize(8).FontColor(MutedColor);
                    t.Span(" of ").FontSize(8).FontColor(MutedColor);
                    t.TotalPages().FontSize(8).FontColor(MutedColor);
                });
            });
        }

        // ── Cell helpers ────────────────────────────────────────────────────

        /// <summary>Standard label cell — grey, small.</summary>
        public static IContainer LabelCell(this IContainer c)
            => c.PaddingVertical(3).PaddingHorizontal(6);

        /// <summary>Right-aligned amount cell in monospace.</summary>
        public static IContainer AmountCell(this IContainer c)
            => c.PaddingVertical(3).PaddingHorizontal(6).AlignRight();

        /// <summary>Header row background.</summary>
        public static IContainer HeaderCell(this IContainer c)
            => c.Background("#e2e8f0").PaddingVertical(4).PaddingHorizontal(6);

        /// <summary>Subtotal row (light bg, bold).</summary>
        public static IContainer SubtotalCell(this IContainer c)
            => c.Background(LightBgColor).PaddingVertical(4).PaddingHorizontal(6);

        // ── Common content blocks ───────────────────────────────────────────

        /// <summary>Two-column key-value list (e.g. for header metadata).</summary>
        public static void KvBlock(this IContainer c, IEnumerable<(string Label, string Value)> rows)
        {
            c.Table(t =>
            {
                t.ColumnsDefinition(d =>
                {
                    d.RelativeColumn(1);
                    d.RelativeColumn(2);
                });
                foreach (var (label, value) in rows)
                {
                    t.Cell().Element(LabelCell).Text(label).FontColor(MutedColor).FontSize(9);
                    t.Cell().Element(LabelCell).Text(value).FontSize(10);
                }
            });
        }

        /// <summary>Format amount as ₹X,XXX with N0 grouping. Null/zero → "—".</summary>
        public static string Money(double v) => v == 0 ? "—" : $"₹{v:N0}";
        public static string Money2(double v) => v == 0 ? "—" : $"₹{v:N2}";
    }
}
